name: BukkitPermissions
version: 1.0
authors: [Jake0oo0]
description: Bukkit Permissions
main: net.cogz.permissions.bukkit.GearzBukkitPermissions
commands:
  permissions:
    description: Permissions command.
