database: gearz_test
host: one.tbnr.pw
port: 27017
channels:
  enabled: true
  list:
    - default
formatting:
  default:
    format: "%player%: %message%"
    permission: "gearz.channels.default"
    default: true
    irc:
      enabled: true
      channels:
        - "#tbnrserver"
    filter: true
irc:
  name: TBNRBot
  server: irc.esper.net
  login: tbnr
  enabled: true
  printout: true
  format: "[%server%]<%sender%>: %message%"
