database: gearz_test
host: one.tbnr.pw
port: 27017
channels:
  enabled: true
  list:
    - default
formatting:
  default:
    format: "%prefix%%player%%suffix%: %message%"
    permission: "gearz.channels.default"
    default: true
    filter: true
irc:
  name: TBNRBot
  server: irc.esper.net
  login: tbnr
  enabled: false
  printout: false
  format: "[%server%]<%sender%>: %message%"
