name: Gearz
version: 1.2
authors: [Twister915, xIGBClutchIx, Thecraftgod, pokuit]
description: o, dem gearz
main: net.tbnr.gearz.Gearz
depend: [ProtocolLib]
load: STARTUP
permissions:
  gearz.test:
    default: op