name: Gearz
version: 1.1
authors: [Twister915, xIGBClutchIx, Thecraftgod, pokuit]
description: o, dem gearz
main: net.tbnr.gearz.Gearz
depend: [ProtocolLib, Vault]
commands:
  nick:
    description: Nickname.
  realname:
    description: Checks a player's real name.
  xp:
    description: Xp
  game:
    description: Game manager command
permissions:
  gearz.test:
    default: op