name: Gearz
version: 1.1
authors: [Twister915, xIGBClutchIx, Thecraftgod, pokuit]
description: o, dem gearz
main: net.tbnr.gearz.Gearz
depend: [ProtocolLib, Vault]
commands:
  nick:
    description: Nickname.
  whois:
    description: Whois.
  xp:
    description: Xp
permissions:
  gearz.test:
    default: op