formats:
  chat-speed: "&cYou're chatting too fast! Slow down!"
  chat-short: "&cThat message is too short!"
  chat-many-words: "&cThat's a lot of short words!"
  chat-long-word: "&cThat's a long word!"
  chat-advertising: "&cNo advertising!"
  chat-gspeed: "&9Chat is cooling down, too much traffic!"
  chat-repeat: "&cYou can't repeat your last message!"
  header-censorlist: "&9Censored Words:"
  chat-muted: "&4The chat is globally muted."
  chat-mute-on: "&6You have muted chat."
  chat-mute-off: "&6You have unmuted chat."
  chat-not-muted: "&cThat chat is not muted!"
  chat-is-muted: "&cThat chat is already muted!"
  minechat-banned: "&cMineChat is banned on &2TBNR!"
  channels: "&4Channels:"
  channel: "&c<channel>"
  switched: "&cYou have switched the the channel: &4<channel>"
  already-on-channel: "&cYou are already on this channel!"
  index-out-of-range: "&cThat's not a valid index!"
  header-motdlist: "&9Motds:"
  removed-motd: "<motd>&c has been removed!"
  added-motd: "<motd>&a has been added!"
  list-motdlist: "&3<index>&a:&r <motd>"
  